
-- create table for prompt
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT 0,
    uuid CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    act VARCHAR(255) NOT NULL,
    prompt VARCHAR(999) NOT NULL,
    is_custom BOOLEAN NOT NULL DEFAULT 1,
    UNIQUE INDEX uuid (uuid)
) CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
