// Code generated by ent, DO NOT EDIT.

package account

import (
	"notionboy/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// Deleted applies equality check predicate on the "deleted" field. It's identical to DeletedEQ.
func Deleted(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeleted, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUUID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserID, v))
}

// DatabaseID applies equality check predicate on the "database_id" field. It's identical to DatabaseIDEQ.
func DatabaseID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDatabaseID, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccessToken, v))
}

// NotionUserID applies equality check predicate on the "notion_user_id" field. It's identical to NotionUserIDEQ.
func NotionUserID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotionUserID, v))
}

// NotionUserEmail applies equality check predicate on the "notion_user_email" field. It's identical to NotionUserEmailEQ.
func NotionUserEmail(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotionUserEmail, v))
}

// IsLatestSchema applies equality check predicate on the "is_latest_schema" field. It's identical to IsLatestSchemaEQ.
func IsLatestSchema(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsLatestSchema, v))
}

// IsOpenaiAPIUser applies equality check predicate on the "is_openai_api_user" field. It's identical to IsOpenaiAPIUserEQ.
func IsOpenaiAPIUser(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsOpenaiAPIUser, v))
}

// OpenaiAPIKey applies equality check predicate on the "openai_api_key" field. It's identical to OpenaiAPIKeyEQ.
func OpenaiAPIKey(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldOpenaiAPIKey, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAPIKey, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsAdmin, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedEQ applies the EQ predicate on the "deleted" field.
func DeletedEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeleted, v))
}

// DeletedNEQ applies the NEQ predicate on the "deleted" field.
func DeletedNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDeleted, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUUID, v))
}

// UUIDIsNil applies the IsNil predicate on the "uuid" field.
func UUIDIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldUUID))
}

// UUIDNotNil applies the NotNil predicate on the "uuid" field.
func UUIDNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldUUID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldUserID, v))
}

// UserTypeEQ applies the EQ predicate on the "user_type" field.
func UserTypeEQ(v UserType) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserType, v))
}

// UserTypeNEQ applies the NEQ predicate on the "user_type" field.
func UserTypeNEQ(v UserType) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUserType, v))
}

// UserTypeIn applies the In predicate on the "user_type" field.
func UserTypeIn(vs ...UserType) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUserType, vs...))
}

// UserTypeNotIn applies the NotIn predicate on the "user_type" field.
func UserTypeNotIn(vs ...UserType) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUserType, vs...))
}

// UserTypeIsNil applies the IsNil predicate on the "user_type" field.
func UserTypeIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldUserType))
}

// UserTypeNotNil applies the NotNil predicate on the "user_type" field.
func UserTypeNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldUserType))
}

// DatabaseIDEQ applies the EQ predicate on the "database_id" field.
func DatabaseIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDatabaseID, v))
}

// DatabaseIDNEQ applies the NEQ predicate on the "database_id" field.
func DatabaseIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDatabaseID, v))
}

// DatabaseIDIn applies the In predicate on the "database_id" field.
func DatabaseIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldDatabaseID, vs...))
}

// DatabaseIDNotIn applies the NotIn predicate on the "database_id" field.
func DatabaseIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldDatabaseID, vs...))
}

// DatabaseIDGT applies the GT predicate on the "database_id" field.
func DatabaseIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldDatabaseID, v))
}

// DatabaseIDGTE applies the GTE predicate on the "database_id" field.
func DatabaseIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldDatabaseID, v))
}

// DatabaseIDLT applies the LT predicate on the "database_id" field.
func DatabaseIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldDatabaseID, v))
}

// DatabaseIDLTE applies the LTE predicate on the "database_id" field.
func DatabaseIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldDatabaseID, v))
}

// DatabaseIDContains applies the Contains predicate on the "database_id" field.
func DatabaseIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldDatabaseID, v))
}

// DatabaseIDHasPrefix applies the HasPrefix predicate on the "database_id" field.
func DatabaseIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldDatabaseID, v))
}

// DatabaseIDHasSuffix applies the HasSuffix predicate on the "database_id" field.
func DatabaseIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldDatabaseID, v))
}

// DatabaseIDIsNil applies the IsNil predicate on the "database_id" field.
func DatabaseIDIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldDatabaseID))
}

// DatabaseIDNotNil applies the NotNil predicate on the "database_id" field.
func DatabaseIDNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldDatabaseID))
}

// DatabaseIDEqualFold applies the EqualFold predicate on the "database_id" field.
func DatabaseIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldDatabaseID, v))
}

// DatabaseIDContainsFold applies the ContainsFold predicate on the "database_id" field.
func DatabaseIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldDatabaseID, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldAccessToken, v))
}

// NotionUserIDEQ applies the EQ predicate on the "notion_user_id" field.
func NotionUserIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotionUserID, v))
}

// NotionUserIDNEQ applies the NEQ predicate on the "notion_user_id" field.
func NotionUserIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldNotionUserID, v))
}

// NotionUserIDIn applies the In predicate on the "notion_user_id" field.
func NotionUserIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldNotionUserID, vs...))
}

// NotionUserIDNotIn applies the NotIn predicate on the "notion_user_id" field.
func NotionUserIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldNotionUserID, vs...))
}

// NotionUserIDGT applies the GT predicate on the "notion_user_id" field.
func NotionUserIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldNotionUserID, v))
}

// NotionUserIDGTE applies the GTE predicate on the "notion_user_id" field.
func NotionUserIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldNotionUserID, v))
}

// NotionUserIDLT applies the LT predicate on the "notion_user_id" field.
func NotionUserIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldNotionUserID, v))
}

// NotionUserIDLTE applies the LTE predicate on the "notion_user_id" field.
func NotionUserIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldNotionUserID, v))
}

// NotionUserIDContains applies the Contains predicate on the "notion_user_id" field.
func NotionUserIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldNotionUserID, v))
}

// NotionUserIDHasPrefix applies the HasPrefix predicate on the "notion_user_id" field.
func NotionUserIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldNotionUserID, v))
}

// NotionUserIDHasSuffix applies the HasSuffix predicate on the "notion_user_id" field.
func NotionUserIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldNotionUserID, v))
}

// NotionUserIDIsNil applies the IsNil predicate on the "notion_user_id" field.
func NotionUserIDIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldNotionUserID))
}

// NotionUserIDNotNil applies the NotNil predicate on the "notion_user_id" field.
func NotionUserIDNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldNotionUserID))
}

// NotionUserIDEqualFold applies the EqualFold predicate on the "notion_user_id" field.
func NotionUserIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldNotionUserID, v))
}

// NotionUserIDContainsFold applies the ContainsFold predicate on the "notion_user_id" field.
func NotionUserIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldNotionUserID, v))
}

// NotionUserEmailEQ applies the EQ predicate on the "notion_user_email" field.
func NotionUserEmailEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotionUserEmail, v))
}

// NotionUserEmailNEQ applies the NEQ predicate on the "notion_user_email" field.
func NotionUserEmailNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldNotionUserEmail, v))
}

// NotionUserEmailIn applies the In predicate on the "notion_user_email" field.
func NotionUserEmailIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldNotionUserEmail, vs...))
}

// NotionUserEmailNotIn applies the NotIn predicate on the "notion_user_email" field.
func NotionUserEmailNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldNotionUserEmail, vs...))
}

// NotionUserEmailGT applies the GT predicate on the "notion_user_email" field.
func NotionUserEmailGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldNotionUserEmail, v))
}

// NotionUserEmailGTE applies the GTE predicate on the "notion_user_email" field.
func NotionUserEmailGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldNotionUserEmail, v))
}

// NotionUserEmailLT applies the LT predicate on the "notion_user_email" field.
func NotionUserEmailLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldNotionUserEmail, v))
}

// NotionUserEmailLTE applies the LTE predicate on the "notion_user_email" field.
func NotionUserEmailLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldNotionUserEmail, v))
}

// NotionUserEmailContains applies the Contains predicate on the "notion_user_email" field.
func NotionUserEmailContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldNotionUserEmail, v))
}

// NotionUserEmailHasPrefix applies the HasPrefix predicate on the "notion_user_email" field.
func NotionUserEmailHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldNotionUserEmail, v))
}

// NotionUserEmailHasSuffix applies the HasSuffix predicate on the "notion_user_email" field.
func NotionUserEmailHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldNotionUserEmail, v))
}

// NotionUserEmailIsNil applies the IsNil predicate on the "notion_user_email" field.
func NotionUserEmailIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldNotionUserEmail))
}

// NotionUserEmailNotNil applies the NotNil predicate on the "notion_user_email" field.
func NotionUserEmailNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldNotionUserEmail))
}

// NotionUserEmailEqualFold applies the EqualFold predicate on the "notion_user_email" field.
func NotionUserEmailEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldNotionUserEmail, v))
}

// NotionUserEmailContainsFold applies the ContainsFold predicate on the "notion_user_email" field.
func NotionUserEmailContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldNotionUserEmail, v))
}

// IsLatestSchemaEQ applies the EQ predicate on the "is_latest_schema" field.
func IsLatestSchemaEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsLatestSchema, v))
}

// IsLatestSchemaNEQ applies the NEQ predicate on the "is_latest_schema" field.
func IsLatestSchemaNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldIsLatestSchema, v))
}

// IsOpenaiAPIUserEQ applies the EQ predicate on the "is_openai_api_user" field.
func IsOpenaiAPIUserEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsOpenaiAPIUser, v))
}

// IsOpenaiAPIUserNEQ applies the NEQ predicate on the "is_openai_api_user" field.
func IsOpenaiAPIUserNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldIsOpenaiAPIUser, v))
}

// OpenaiAPIKeyEQ applies the EQ predicate on the "openai_api_key" field.
func OpenaiAPIKeyEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyNEQ applies the NEQ predicate on the "openai_api_key" field.
func OpenaiAPIKeyNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyIn applies the In predicate on the "openai_api_key" field.
func OpenaiAPIKeyIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldOpenaiAPIKey, vs...))
}

// OpenaiAPIKeyNotIn applies the NotIn predicate on the "openai_api_key" field.
func OpenaiAPIKeyNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldOpenaiAPIKey, vs...))
}

// OpenaiAPIKeyGT applies the GT predicate on the "openai_api_key" field.
func OpenaiAPIKeyGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyGTE applies the GTE predicate on the "openai_api_key" field.
func OpenaiAPIKeyGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyLT applies the LT predicate on the "openai_api_key" field.
func OpenaiAPIKeyLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyLTE applies the LTE predicate on the "openai_api_key" field.
func OpenaiAPIKeyLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyContains applies the Contains predicate on the "openai_api_key" field.
func OpenaiAPIKeyContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyHasPrefix applies the HasPrefix predicate on the "openai_api_key" field.
func OpenaiAPIKeyHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyHasSuffix applies the HasSuffix predicate on the "openai_api_key" field.
func OpenaiAPIKeyHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyIsNil applies the IsNil predicate on the "openai_api_key" field.
func OpenaiAPIKeyIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldOpenaiAPIKey))
}

// OpenaiAPIKeyNotNil applies the NotNil predicate on the "openai_api_key" field.
func OpenaiAPIKeyNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldOpenaiAPIKey))
}

// OpenaiAPIKeyEqualFold applies the EqualFold predicate on the "openai_api_key" field.
func OpenaiAPIKeyEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldOpenaiAPIKey, v))
}

// OpenaiAPIKeyContainsFold applies the ContainsFold predicate on the "openai_api_key" field.
func OpenaiAPIKeyContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldOpenaiAPIKey, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyIsNil applies the IsNil predicate on the "api_key" field.
func APIKeyIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldAPIKey))
}

// APIKeyNotNil applies the NotNil predicate on the "api_key" field.
func APIKeyNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldAPIKey))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldIsAdmin, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		p(s.Not())
	})
}
