// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: model/conversation.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := MessageValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ConversationId

	if utf8.RuneCountInString(m.GetRequest()) < 1 {
		err := MessageValidationError{
			field:  "Request",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetResponse()) < 1 {
		err := MessageValidationError{
			field:  "Response",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for TokenUsage

	// no validation rules for Model

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on ConversationWithoutMessages with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationWithoutMessages) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationWithoutMessages with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationWithoutMessagesMultiError, or nil if none found.
func (m *ConversationWithoutMessages) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationWithoutMessages) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := ConversationWithoutMessagesValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for Instruction

	// no validation rules for Title

	if len(errors) > 0 {
		return ConversationWithoutMessagesMultiError(errors)
	}

	return nil
}

// ConversationWithoutMessagesMultiError is an error wrapping multiple
// validation errors returned by ConversationWithoutMessages.ValidateAll() if
// the designated constraints aren't met.
type ConversationWithoutMessagesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationWithoutMessagesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationWithoutMessagesMultiError) AllErrors() []error { return m }

// ConversationWithoutMessagesValidationError is the validation error returned
// by ConversationWithoutMessages.Validate if the designated constraints
// aren't met.
type ConversationWithoutMessagesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationWithoutMessagesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationWithoutMessagesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationWithoutMessagesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationWithoutMessagesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationWithoutMessagesValidationError) ErrorName() string {
	return "ConversationWithoutMessagesValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationWithoutMessagesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationWithoutMessages.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationWithoutMessagesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationWithoutMessagesValidationError{}

// Validate checks the field values on Conversation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Conversation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Conversation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConversationMultiError, or
// nil if none found.
func (m *Conversation) ValidateAll() error {
	return m.validate(true)
}

func (m *Conversation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := ConversationValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for Instruction

	// no validation rules for Title

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConversationValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConversationValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConversationValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TokenUsage

	if len(errors) > 0 {
		return ConversationMultiError(errors)
	}

	return nil
}

// ConversationMultiError is an error wrapping multiple validation errors
// returned by Conversation.ValidateAll() if the designated constraints aren't met.
type ConversationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationMultiError) AllErrors() []error { return m }

// ConversationValidationError is the validation error returned by
// Conversation.Validate if the designated constraints aren't met.
type ConversationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationValidationError) ErrorName() string { return "ConversationValidationError" }

// Error satisfies the builtin error interface
func (e ConversationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationValidationError{}

// Validate checks the field values on ListConversationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListConversationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConversationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConversationsRequestMultiError, or nil if none found.
func (m *ListConversationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConversationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListConversationsRequestMultiError(errors)
	}

	return nil
}

// ListConversationsRequestMultiError is an error wrapping multiple validation
// errors returned by ListConversationsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListConversationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConversationsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConversationsRequestMultiError) AllErrors() []error { return m }

// ListConversationsRequestValidationError is the validation error returned by
// ListConversationsRequest.Validate if the designated constraints aren't met.
type ListConversationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConversationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConversationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConversationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConversationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConversationsRequestValidationError) ErrorName() string {
	return "ListConversationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListConversationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConversationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConversationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConversationsRequestValidationError{}

// Validate checks the field values on ListConversationsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListConversationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConversationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConversationsResponseMultiError, or nil if none found.
func (m *ListConversationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConversationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetConversations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListConversationsResponseValidationError{
						field:  fmt.Sprintf("Conversations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListConversationsResponseValidationError{
						field:  fmt.Sprintf("Conversations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListConversationsResponseValidationError{
					field:  fmt.Sprintf("Conversations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListConversationsResponseMultiError(errors)
	}

	return nil
}

// ListConversationsResponseMultiError is an error wrapping multiple validation
// errors returned by ListConversationsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListConversationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConversationsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConversationsResponseMultiError) AllErrors() []error { return m }

// ListConversationsResponseValidationError is the validation error returned by
// ListConversationsResponse.Validate if the designated constraints aren't met.
type ListConversationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConversationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConversationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConversationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConversationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConversationsResponseValidationError) ErrorName() string {
	return "ListConversationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListConversationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConversationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConversationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConversationsResponseValidationError{}

// Validate checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetConversationRequestMultiError, or nil if none found.
func (m *GetConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetConversationRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetConversationRequestMultiError(errors)
	}

	return nil
}

// GetConversationRequestMultiError is an error wrapping multiple validation
// errors returned by GetConversationRequest.ValidateAll() if the designated
// constraints aren't met.
type GetConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetConversationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetConversationRequestMultiError) AllErrors() []error { return m }

// GetConversationRequestValidationError is the validation error returned by
// GetConversationRequest.Validate if the designated constraints aren't met.
type GetConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetConversationRequestValidationError) ErrorName() string {
	return "GetConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetConversationRequestValidationError{}

// Validate checks the field values on CreateConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateConversationRequestMultiError, or nil if none found.
func (m *CreateConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Instruction

	// no validation rules for Title

	if len(errors) > 0 {
		return CreateConversationRequestMultiError(errors)
	}

	return nil
}

// CreateConversationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateConversationRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateConversationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateConversationRequestMultiError) AllErrors() []error { return m }

// CreateConversationRequestValidationError is the validation error returned by
// CreateConversationRequest.Validate if the designated constraints aren't met.
type CreateConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateConversationRequestValidationError) ErrorName() string {
	return "CreateConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateConversationRequestValidationError{}

// Validate checks the field values on UpdateConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateConversationRequestMultiError, or nil if none found.
func (m *UpdateConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateConversationRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Instruction

	// no validation rules for Title

	if len(errors) > 0 {
		return UpdateConversationRequestMultiError(errors)
	}

	return nil
}

// UpdateConversationRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateConversationRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateConversationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateConversationRequestMultiError) AllErrors() []error { return m }

// UpdateConversationRequestValidationError is the validation error returned by
// UpdateConversationRequest.Validate if the designated constraints aren't met.
type UpdateConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateConversationRequestValidationError) ErrorName() string {
	return "UpdateConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateConversationRequestValidationError{}

// Validate checks the field values on DeleteConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteConversationRequestMultiError, or nil if none found.
func (m *DeleteConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteConversationRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteConversationRequestMultiError(errors)
	}

	return nil
}

// DeleteConversationRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteConversationRequest.ValidateAll() if the
// designated constraints aren't met.
type DeleteConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteConversationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteConversationRequestMultiError) AllErrors() []error { return m }

// DeleteConversationRequestValidationError is the validation error returned by
// DeleteConversationRequest.Validate if the designated constraints aren't met.
type DeleteConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteConversationRequestValidationError) ErrorName() string {
	return "DeleteConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteConversationRequestValidationError{}

// Validate checks the field values on CreateMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMessageRequestMultiError, or nil if none found.
func (m *CreateMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConversationId

	// no validation rules for Model

	// no validation rules for Request

	// no validation rules for Temperature

	// no validation rules for MaxTokens

	if len(errors) > 0 {
		return CreateMessageRequestMultiError(errors)
	}

	return nil
}

// CreateMessageRequestMultiError is an error wrapping multiple validation
// errors returned by CreateMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMessageRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMessageRequestMultiError) AllErrors() []error { return m }

// CreateMessageRequestValidationError is the validation error returned by
// CreateMessageRequest.Validate if the designated constraints aren't met.
type CreateMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMessageRequestValidationError) ErrorName() string {
	return "CreateMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMessageRequestValidationError{}

// Validate checks the field values on ListMessagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMessagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMessagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMessagesRequestMultiError, or nil if none found.
func (m *ListMessagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMessagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConversationId

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListMessagesRequestMultiError(errors)
	}

	return nil
}

// ListMessagesRequestMultiError is an error wrapping multiple validation
// errors returned by ListMessagesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListMessagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMessagesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMessagesRequestMultiError) AllErrors() []error { return m }

// ListMessagesRequestValidationError is the validation error returned by
// ListMessagesRequest.Validate if the designated constraints aren't met.
type ListMessagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMessagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMessagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMessagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMessagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMessagesRequestValidationError) ErrorName() string {
	return "ListMessagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMessagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMessagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMessagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMessagesRequestValidationError{}

// Validate checks the field values on ListMessagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMessagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMessagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMessagesResponseMultiError, or nil if none found.
func (m *ListMessagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMessagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMessagesResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMessagesResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMessagesResponseValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMessagesResponseMultiError(errors)
	}

	return nil
}

// ListMessagesResponseMultiError is an error wrapping multiple validation
// errors returned by ListMessagesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMessagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMessagesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMessagesResponseMultiError) AllErrors() []error { return m }

// ListMessagesResponseValidationError is the validation error returned by
// ListMessagesResponse.Validate if the designated constraints aren't met.
type ListMessagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMessagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMessagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMessagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMessagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMessagesResponseValidationError) ErrorName() string {
	return "ListMessagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMessagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMessagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMessagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMessagesResponseValidationError{}

// Validate checks the field values on GetMessageRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMessageRequestMultiError, or nil if none found.
func (m *GetMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetMessageRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ConversationId

	if len(errors) > 0 {
		return GetMessageRequestMultiError(errors)
	}

	return nil
}

// GetMessageRequestMultiError is an error wrapping multiple validation errors
// returned by GetMessageRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMessageRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMessageRequestMultiError) AllErrors() []error { return m }

// GetMessageRequestValidationError is the validation error returned by
// GetMessageRequest.Validate if the designated constraints aren't met.
type GetMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMessageRequestValidationError) ErrorName() string {
	return "GetMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMessageRequestValidationError{}

// Validate checks the field values on DeleteMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMessageRequestMultiError, or nil if none found.
func (m *DeleteMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteMessageRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ConversationId

	if len(errors) > 0 {
		return DeleteMessageRequestMultiError(errors)
	}

	return nil
}

// DeleteMessageRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMessageRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMessageRequestMultiError) AllErrors() []error { return m }

// DeleteMessageRequestValidationError is the validation error returned by
// DeleteMessageRequest.Validate if the designated constraints aren't met.
type DeleteMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMessageRequestValidationError) ErrorName() string {
	return "DeleteMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMessageRequestValidationError{}
