// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notionboy/db/ent/account"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ac *AccountCreate) SetCreatedAt(t time.Time) *AccountCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreatedAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AccountCreate) SetUpdatedAt(t time.Time) *AccountCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableUpdatedAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetDeleted sets the "deleted" field.
func (ac *AccountCreate) SetDeleted(b bool) *AccountCreate {
	ac.mutation.SetDeleted(b)
	return ac
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (ac *AccountCreate) SetNillableDeleted(b *bool) *AccountCreate {
	if b != nil {
		ac.SetDeleted(*b)
	}
	return ac
}

// SetUserID sets the "user_id" field.
func (ac *AccountCreate) SetUserID(s string) *AccountCreate {
	ac.mutation.SetUserID(s)
	return ac
}

// SetUserType sets the "user_type" field.
func (ac *AccountCreate) SetUserType(at account.UserType) *AccountCreate {
	ac.mutation.SetUserType(at)
	return ac
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (ac *AccountCreate) SetNillableUserType(at *account.UserType) *AccountCreate {
	if at != nil {
		ac.SetUserType(*at)
	}
	return ac
}

// SetDatabaseID sets the "database_id" field.
func (ac *AccountCreate) SetDatabaseID(s string) *AccountCreate {
	ac.mutation.SetDatabaseID(s)
	return ac
}

// SetAccessToken sets the "access_token" field.
func (ac *AccountCreate) SetAccessToken(s string) *AccountCreate {
	ac.mutation.SetAccessToken(s)
	return ac
}

// SetIsLatestSchema sets the "is_latest_schema" field.
func (ac *AccountCreate) SetIsLatestSchema(b bool) *AccountCreate {
	ac.mutation.SetIsLatestSchema(b)
	return ac
}

// SetNillableIsLatestSchema sets the "is_latest_schema" field if the given value is not nil.
func (ac *AccountCreate) SetNillableIsLatestSchema(b *bool) *AccountCreate {
	if b != nil {
		ac.SetIsLatestSchema(*b)
	}
	return ac
}

// Mutation returns the AccountMutation object of the builder.
func (ac *AccountCreate) Mutation() *AccountMutation {
	return ac.mutation
}

// Save creates the Account in the database.
func (ac *AccountCreate) Save(ctx context.Context) (*Account, error) {
	var (
		err  error
		node *Account
	)
	ac.defaults()
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ac.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Account)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AccountCreate) defaults() {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.Deleted(); !ok {
		v := account.DefaultDeleted
		ac.mutation.SetDeleted(v)
	}
	if _, ok := ac.mutation.UserType(); !ok {
		v := account.DefaultUserType
		ac.mutation.SetUserType(v)
	}
	if _, ok := ac.mutation.IsLatestSchema(); !ok {
		v := account.DefaultIsLatestSchema
		ac.mutation.SetIsLatestSchema(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountCreate) check() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	if _, ok := ac.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "Account.deleted"`)}
	}
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Account.user_id"`)}
	}
	if v, ok := ac.mutation.UserType(); ok {
		if err := account.UserTypeValidator(v); err != nil {
			return &ValidationError{Name: "user_type", err: fmt.Errorf(`ent: validator failed for field "Account.user_type": %w`, err)}
		}
	}
	if _, ok := ac.mutation.DatabaseID(); !ok {
		return &ValidationError{Name: "database_id", err: errors.New(`ent: missing required field "Account.database_id"`)}
	}
	if v, ok := ac.mutation.DatabaseID(); ok {
		if err := account.DatabaseIDValidator(v); err != nil {
			return &ValidationError{Name: "database_id", err: fmt.Errorf(`ent: validator failed for field "Account.database_id": %w`, err)}
		}
	}
	if _, ok := ac.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "Account.access_token"`)}
	}
	if v, ok := ac.mutation.AccessToken(); ok {
		if err := account.AccessTokenValidator(v); err != nil {
			return &ValidationError{Name: "access_token", err: fmt.Errorf(`ent: validator failed for field "Account.access_token": %w`, err)}
		}
	}
	if _, ok := ac.mutation.IsLatestSchema(); !ok {
		return &ValidationError{Name: "is_latest_schema", err: errors.New(`ent: missing required field "Account.is_latest_schema"`)}
	}
	return nil
}

func (ac *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: account.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: account.FieldID,
			},
		}
	)
	_spec.OnConflict = ac.conflict
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.Deleted(); ok {
		_spec.SetField(account.FieldDeleted, field.TypeBool, value)
		_node.Deleted = value
	}
	if value, ok := ac.mutation.UserID(); ok {
		_spec.SetField(account.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := ac.mutation.UserType(); ok {
		_spec.SetField(account.FieldUserType, field.TypeEnum, value)
		_node.UserType = value
	}
	if value, ok := ac.mutation.DatabaseID(); ok {
		_spec.SetField(account.FieldDatabaseID, field.TypeString, value)
		_node.DatabaseID = value
	}
	if value, ok := ac.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := ac.mutation.IsLatestSchema(); ok {
		_spec.SetField(account.FieldIsLatestSchema, field.TypeBool, value)
		_node.IsLatestSchema = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ac *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	ac.conflict = opts
	return &AccountUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: ac,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsert) SetUpdatedAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedAt() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedAt)
	return u
}

// SetDeleted sets the "deleted" field.
func (u *AccountUpsert) SetDeleted(v bool) *AccountUpsert {
	u.Set(account.FieldDeleted, v)
	return u
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *AccountUpsert) UpdateDeleted() *AccountUpsert {
	u.SetExcluded(account.FieldDeleted)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsert) SetUserID(v string) *AccountUpsert {
	u.Set(account.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUserID() *AccountUpsert {
	u.SetExcluded(account.FieldUserID)
	return u
}

// SetUserType sets the "user_type" field.
func (u *AccountUpsert) SetUserType(v account.UserType) *AccountUpsert {
	u.Set(account.FieldUserType, v)
	return u
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUserType() *AccountUpsert {
	u.SetExcluded(account.FieldUserType)
	return u
}

// ClearUserType clears the value of the "user_type" field.
func (u *AccountUpsert) ClearUserType() *AccountUpsert {
	u.SetNull(account.FieldUserType)
	return u
}

// SetDatabaseID sets the "database_id" field.
func (u *AccountUpsert) SetDatabaseID(v string) *AccountUpsert {
	u.Set(account.FieldDatabaseID, v)
	return u
}

// UpdateDatabaseID sets the "database_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateDatabaseID() *AccountUpsert {
	u.SetExcluded(account.FieldDatabaseID)
	return u
}

// SetAccessToken sets the "access_token" field.
func (u *AccountUpsert) SetAccessToken(v string) *AccountUpsert {
	u.Set(account.FieldAccessToken, v)
	return u
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AccountUpsert) UpdateAccessToken() *AccountUpsert {
	u.SetExcluded(account.FieldAccessToken)
	return u
}

// SetIsLatestSchema sets the "is_latest_schema" field.
func (u *AccountUpsert) SetIsLatestSchema(v bool) *AccountUpsert {
	u.Set(account.FieldIsLatestSchema, v)
	return u
}

// UpdateIsLatestSchema sets the "is_latest_schema" field to the value that was provided on create.
func (u *AccountUpsert) UpdateIsLatestSchema() *AccountUpsert {
	u.SetExcluded(account.FieldIsLatestSchema)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertOne) SetUpdatedAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeleted sets the "deleted" field.
func (u *AccountUpsertOne) SetDeleted(v bool) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateDeleted() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDeleted()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsertOne) SetUserID(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUserID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserID()
	})
}

// SetUserType sets the "user_type" field.
func (u *AccountUpsertOne) SetUserType(v account.UserType) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserType(v)
	})
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUserType() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserType()
	})
}

// ClearUserType clears the value of the "user_type" field.
func (u *AccountUpsertOne) ClearUserType() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearUserType()
	})
}

// SetDatabaseID sets the "database_id" field.
func (u *AccountUpsertOne) SetDatabaseID(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetDatabaseID(v)
	})
}

// UpdateDatabaseID sets the "database_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateDatabaseID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDatabaseID()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *AccountUpsertOne) SetAccessToken(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateAccessToken() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAccessToken()
	})
}

// SetIsLatestSchema sets the "is_latest_schema" field.
func (u *AccountUpsertOne) SetIsLatestSchema(v bool) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetIsLatestSchema(v)
	})
}

// UpdateIsLatestSchema sets the "is_latest_schema" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateIsLatestSchema() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateIsLatestSchema()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (acb *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Account, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (acb *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	acb.conflict = opts
	return &AccountUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: acb,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeleted sets the "deleted" field.
func (u *AccountUpsertBulk) SetDeleted(v bool) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateDeleted() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDeleted()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsertBulk) SetUserID(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUserID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserID()
	})
}

// SetUserType sets the "user_type" field.
func (u *AccountUpsertBulk) SetUserType(v account.UserType) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserType(v)
	})
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUserType() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserType()
	})
}

// ClearUserType clears the value of the "user_type" field.
func (u *AccountUpsertBulk) ClearUserType() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearUserType()
	})
}

// SetDatabaseID sets the "database_id" field.
func (u *AccountUpsertBulk) SetDatabaseID(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetDatabaseID(v)
	})
}

// UpdateDatabaseID sets the "database_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateDatabaseID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDatabaseID()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *AccountUpsertBulk) SetAccessToken(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateAccessToken() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAccessToken()
	})
}

// SetIsLatestSchema sets the "is_latest_schema" field.
func (u *AccountUpsertBulk) SetIsLatestSchema(v bool) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetIsLatestSchema(v)
	})
}

// UpdateIsLatestSchema sets the "is_latest_schema" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateIsLatestSchema() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateIsLatestSchema()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
