// Code generated by ent, DO NOT EDIT.

package ent

import (
	"notionboy/db/ent/account"
	"notionboy/db/ent/chathistory"
	"notionboy/db/ent/conversation"
	"notionboy/db/ent/conversationmessage"
	"notionboy/db/ent/order"
	"notionboy/db/ent/product"
	"notionboy/db/ent/quota"
	"notionboy/db/ent/schema"
	"notionboy/db/ent/wechatsession"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountMixinFields1 := accountMixin[1].Fields()
	_ = accountMixinFields1
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescDeleted is the schema descriptor for deleted field.
	accountDescDeleted := accountMixinFields1[0].Descriptor()
	// account.DefaultDeleted holds the default value on creation for the deleted field.
	account.DefaultDeleted = accountDescDeleted.Default.(bool)
	// accountDescIsLatestSchema is the schema descriptor for is_latest_schema field.
	accountDescIsLatestSchema := accountFields[7].Descriptor()
	// account.DefaultIsLatestSchema holds the default value on creation for the is_latest_schema field.
	account.DefaultIsLatestSchema = accountDescIsLatestSchema.Default.(bool)
	// accountDescIsOpenaiAPIUser is the schema descriptor for is_openai_api_user field.
	accountDescIsOpenaiAPIUser := accountFields[8].Descriptor()
	// account.DefaultIsOpenaiAPIUser holds the default value on creation for the is_openai_api_user field.
	account.DefaultIsOpenaiAPIUser = accountDescIsOpenaiAPIUser.Default.(bool)
	// accountDescIsAdmin is the schema descriptor for is_admin field.
	accountDescIsAdmin := accountFields[11].Descriptor()
	// account.DefaultIsAdmin holds the default value on creation for the is_admin field.
	account.DefaultIsAdmin = accountDescIsAdmin.Default.(bool)
	chathistoryMixin := schema.ChatHistory{}.Mixin()
	chathistoryMixinFields0 := chathistoryMixin[0].Fields()
	_ = chathistoryMixinFields0
	chathistoryMixinFields1 := chathistoryMixin[1].Fields()
	_ = chathistoryMixinFields1
	chathistoryFields := schema.ChatHistory{}.Fields()
	_ = chathistoryFields
	// chathistoryDescCreatedAt is the schema descriptor for created_at field.
	chathistoryDescCreatedAt := chathistoryMixinFields0[0].Descriptor()
	// chathistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	chathistory.DefaultCreatedAt = chathistoryDescCreatedAt.Default.(func() time.Time)
	// chathistoryDescUpdatedAt is the schema descriptor for updated_at field.
	chathistoryDescUpdatedAt := chathistoryMixinFields0[1].Descriptor()
	// chathistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chathistory.DefaultUpdatedAt = chathistoryDescUpdatedAt.Default.(func() time.Time)
	// chathistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chathistory.UpdateDefaultUpdatedAt = chathistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// chathistoryDescDeleted is the schema descriptor for deleted field.
	chathistoryDescDeleted := chathistoryMixinFields1[0].Descriptor()
	// chathistory.DefaultDeleted holds the default value on creation for the deleted field.
	chathistory.DefaultDeleted = chathistoryDescDeleted.Default.(bool)
	conversationMixin := schema.Conversation{}.Mixin()
	conversationMixinFields0 := conversationMixin[0].Fields()
	_ = conversationMixinFields0
	conversationMixinFields1 := conversationMixin[1].Fields()
	_ = conversationMixinFields1
	conversationFields := schema.Conversation{}.Fields()
	_ = conversationFields
	// conversationDescCreatedAt is the schema descriptor for created_at field.
	conversationDescCreatedAt := conversationMixinFields0[0].Descriptor()
	// conversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversation.DefaultCreatedAt = conversationDescCreatedAt.Default.(func() time.Time)
	// conversationDescUpdatedAt is the schema descriptor for updated_at field.
	conversationDescUpdatedAt := conversationMixinFields0[1].Descriptor()
	// conversation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	conversation.DefaultUpdatedAt = conversationDescUpdatedAt.Default.(func() time.Time)
	// conversation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	conversation.UpdateDefaultUpdatedAt = conversationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// conversationDescDeleted is the schema descriptor for deleted field.
	conversationDescDeleted := conversationMixinFields1[0].Descriptor()
	// conversation.DefaultDeleted holds the default value on creation for the deleted field.
	conversation.DefaultDeleted = conversationDescDeleted.Default.(bool)
	// conversationDescTokenUsage is the schema descriptor for token_usage field.
	conversationDescTokenUsage := conversationFields[4].Descriptor()
	// conversation.DefaultTokenUsage holds the default value on creation for the token_usage field.
	conversation.DefaultTokenUsage = conversationDescTokenUsage.Default.(int64)
	conversationmessageMixin := schema.ConversationMessage{}.Mixin()
	conversationmessageMixinFields0 := conversationmessageMixin[0].Fields()
	_ = conversationmessageMixinFields0
	conversationmessageMixinFields1 := conversationmessageMixin[1].Fields()
	_ = conversationmessageMixinFields1
	conversationmessageFields := schema.ConversationMessage{}.Fields()
	_ = conversationmessageFields
	// conversationmessageDescCreatedAt is the schema descriptor for created_at field.
	conversationmessageDescCreatedAt := conversationmessageMixinFields0[0].Descriptor()
	// conversationmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversationmessage.DefaultCreatedAt = conversationmessageDescCreatedAt.Default.(func() time.Time)
	// conversationmessageDescUpdatedAt is the schema descriptor for updated_at field.
	conversationmessageDescUpdatedAt := conversationmessageMixinFields0[1].Descriptor()
	// conversationmessage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	conversationmessage.DefaultUpdatedAt = conversationmessageDescUpdatedAt.Default.(func() time.Time)
	// conversationmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	conversationmessage.UpdateDefaultUpdatedAt = conversationmessageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// conversationmessageDescDeleted is the schema descriptor for deleted field.
	conversationmessageDescDeleted := conversationmessageMixinFields1[0].Descriptor()
	// conversationmessage.DefaultDeleted holds the default value on creation for the deleted field.
	conversationmessage.DefaultDeleted = conversationmessageDescDeleted.Default.(bool)
	// conversationmessageDescModel is the schema descriptor for model field.
	conversationmessageDescModel := conversationmessageFields[6].Descriptor()
	// conversationmessage.DefaultModel holds the default value on creation for the model field.
	conversationmessage.DefaultModel = conversationmessageDescModel.Default.(string)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderMixinFields1 := orderMixin[1].Fields()
	_ = orderMixinFields1
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescDeleted is the schema descriptor for deleted field.
	orderDescDeleted := orderMixinFields1[0].Descriptor()
	// order.DefaultDeleted holds the default value on creation for the deleted field.
	order.DefaultDeleted = orderDescDeleted.Default.(bool)
	productMixin := schema.Product{}.Mixin()
	productMixinFields0 := productMixin[0].Fields()
	_ = productMixinFields0
	productMixinFields1 := productMixin[1].Fields()
	_ = productMixinFields1
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productMixinFields0[0].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productMixinFields0[1].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescDeleted is the schema descriptor for deleted field.
	productDescDeleted := productMixinFields1[0].Descriptor()
	// product.DefaultDeleted holds the default value on creation for the deleted field.
	product.DefaultDeleted = productDescDeleted.Default.(bool)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[1].Descriptor()
	// product.DefaultName holds the default value on creation for the name field.
	product.DefaultName = productDescName.Default.(string)
	// productDescToken is the schema descriptor for token field.
	productDescToken := productFields[4].Descriptor()
	// product.DefaultToken holds the default value on creation for the token field.
	product.DefaultToken = productDescToken.Default.(int64)
	// productDescStorage is the schema descriptor for storage field.
	productDescStorage := productFields[5].Descriptor()
	// product.DefaultStorage holds the default value on creation for the storage field.
	product.DefaultStorage = productDescStorage.Default.(int64)
	quotaMixin := schema.Quota{}.Mixin()
	quotaMixinFields0 := quotaMixin[0].Fields()
	_ = quotaMixinFields0
	quotaMixinFields1 := quotaMixin[1].Fields()
	_ = quotaMixinFields1
	quotaFields := schema.Quota{}.Fields()
	_ = quotaFields
	// quotaDescCreatedAt is the schema descriptor for created_at field.
	quotaDescCreatedAt := quotaMixinFields0[0].Descriptor()
	// quota.DefaultCreatedAt holds the default value on creation for the created_at field.
	quota.DefaultCreatedAt = quotaDescCreatedAt.Default.(func() time.Time)
	// quotaDescUpdatedAt is the schema descriptor for updated_at field.
	quotaDescUpdatedAt := quotaMixinFields0[1].Descriptor()
	// quota.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quota.DefaultUpdatedAt = quotaDescUpdatedAt.Default.(func() time.Time)
	// quota.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quota.UpdateDefaultUpdatedAt = quotaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// quotaDescDeleted is the schema descriptor for deleted field.
	quotaDescDeleted := quotaMixinFields1[0].Descriptor()
	// quota.DefaultDeleted holds the default value on creation for the deleted field.
	quota.DefaultDeleted = quotaDescDeleted.Default.(bool)
	// quotaDescTokenUsed is the schema descriptor for token_used field.
	quotaDescTokenUsed := quotaFields[4].Descriptor()
	// quota.DefaultTokenUsed holds the default value on creation for the token_used field.
	quota.DefaultTokenUsed = quotaDescTokenUsed.Default.(int64)
	wechatsessionMixin := schema.WechatSession{}.Mixin()
	wechatsessionMixinFields0 := wechatsessionMixin[0].Fields()
	_ = wechatsessionMixinFields0
	wechatsessionMixinFields1 := wechatsessionMixin[1].Fields()
	_ = wechatsessionMixinFields1
	wechatsessionFields := schema.WechatSession{}.Fields()
	_ = wechatsessionFields
	// wechatsessionDescCreatedAt is the schema descriptor for created_at field.
	wechatsessionDescCreatedAt := wechatsessionMixinFields0[0].Descriptor()
	// wechatsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	wechatsession.DefaultCreatedAt = wechatsessionDescCreatedAt.Default.(func() time.Time)
	// wechatsessionDescUpdatedAt is the schema descriptor for updated_at field.
	wechatsessionDescUpdatedAt := wechatsessionMixinFields0[1].Descriptor()
	// wechatsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wechatsession.DefaultUpdatedAt = wechatsessionDescUpdatedAt.Default.(func() time.Time)
	// wechatsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wechatsession.UpdateDefaultUpdatedAt = wechatsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// wechatsessionDescDeleted is the schema descriptor for deleted field.
	wechatsessionDescDeleted := wechatsessionMixinFields1[0].Descriptor()
	// wechatsession.DefaultDeleted holds the default value on creation for the deleted field.
	wechatsession.DefaultDeleted = wechatsessionDescDeleted.Default.(bool)
}
